name: task1
description: "Internal business demo — orders and barcode QC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/products.json
